export type Category = "Events" | "Experiences" | "Services" | "Groups" | "Fundraisers" | "Volunteers";

export type Status = "published" | "pending" | "rejected";

export interface Listing {
  id: string;
  title: string;
  category: Category;
  subcategory: string;
  description: string;
  date?: string;
  time?: string;
  location: string;
  city: string;
  state: string;
  cost: string;
  seniorDiscount?: boolean;
  contact?: string;
  url?: string;
  tags: string[];
  status: Status;
  submittedBy: "curator" | "community";
  createdAt: string;
}

let listings: Listing[] = [

  // ── CHESTER ──────────────────────────────────────────────────────────────

  {
    id: "c1",
    title: "Chester-Hadlyme Ferry Crossing",
    category: "Experiences",
    subcategory: "Adventure Days",
    description: "Hop aboard the second-oldest continuously operating ferry in the country. The Selden III carries you across the Connecticut River in just a few minutes — a small trip that feels like stepping back in time. Runs spring through fall.",
    location: "Ferry Landing, 148 River Rd",
    city: "Chester",
    state: "CT",
    cost: "$3 per person",
    tags: ["ferry", "river", "historic", "family", "outdoors"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "c2",
    title: "Saturday Morning at the Chester Farmers Market",
    category: "Events",
    subcategory: "Community Gathering",
    description: "Fresh produce, local honey, handmade breads, cut flowers, and familiar faces every Saturday morning in the village center. The heart of Chester's weekly rhythm.",
    date: "2026-06-13",
    time: "9:00 AM",
    location: "Chester Town Center, Route 154",
    city: "Chester",
    state: "CT",
    cost: "Free to attend",
    tags: ["farmers market", "local food", "weekly", "community"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "c3",
    title: "Gallery Crawl — Chester Village Arts District",
    category: "Experiences",
    subcategory: "Self-Guided",
    description: "Chester's Main Street packs more galleries per block than almost anywhere in Connecticut. Pick up a gallery map at the Pattaconk Tavern and wander at your own pace — ceramics, painting, sculpture, and jewelry from working artists.",
    location: "Main St, Chester Village",
    city: "Chester",
    state: "CT",
    cost: "Free",
    tags: ["art", "galleries", "self-guided", "walking", "village"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "c4",
    title: "Chester Creative Arts Summer Concert Series",
    category: "Events",
    subcategory: "Music",
    description: "Free outdoor concerts on the Chester Town Green all summer long. Bring a lawn chair or blanket. Local and regional musicians play folk, jazz, bluegrass, and more. Community potluck follows some shows.",
    date: "2026-06-20",
    time: "6:30 PM",
    location: "Chester Town Green",
    city: "Chester",
    state: "CT",
    cost: "Free",
    tags: ["music", "outdoor", "summer", "community", "concerts"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "c5",
    title: "Connecticut River Paddle Group — Chester Launch",
    category: "Groups",
    subcategory: "Walking Groups",
    description: "Kayak and canoe paddlers of all experience levels meet at the Chester town boat launch every Wednesday morning. We paddle together for 1–2 hours on the Connecticut River. Bring your own boat or ask about loaner options.",
    location: "Chester Boat Launch, Ferry Rd",
    city: "Chester",
    state: "CT",
    cost: "Free",
    contact: "ctriverpaddlers@gmail.com",
    tags: ["kayak", "paddling", "river", "weekly", "outdoors"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── DEEP RIVER ──────────────────────────────────────────────────────────

  {
    id: "dr1",
    title: "Deep River Ancient Fife & Drum Muster",
    category: "Events",
    subcategory: "Community Gathering",
    description: "One of the oldest and largest fife and drum musters in the world, held every July in Deep River. Dozens of corps from across the country march through town in period dress. A genuine Connecticut tradition unlike anything else.",
    date: "2026-07-19",
    time: "10:00 AM",
    location: "Main Street, Deep River",
    city: "Deep River",
    state: "CT",
    cost: "Free",
    tags: ["fife and drum", "parade", "historic", "tradition", "July"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "dr2",
    title: "Wangunk Meadows Trail Walk",
    category: "Experiences",
    subcategory: "Field Quests",
    description: "A quiet gem tucked along the river. The Wangunk Meadows preserve offers flat, easy walking through wetlands and meadows with excellent bird watching — great blue herons, ospreys, and red-winged blackbirds are common. Bring binoculars.",
    location: "Wangunk Meadows Trailhead, Plattwood Rd",
    city: "Deep River",
    state: "CT",
    cost: "Free",
    tags: ["birding", "walking", "nature", "meadows", "river"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "dr3",
    title: "Deep River Library Book Group",
    category: "Groups",
    subcategory: "Book Clubs",
    description: "Friendly monthly book discussion at the Deep River Public Library. All reading tastes welcome. Books available through the library system. Meets the second Thursday of each month at 6:30 PM. Coffee provided.",
    location: "Deep River Public Library, 150 Main St",
    city: "Deep River",
    state: "CT",
    cost: "Free",
    contact: "library@deepriverct.us",
    tags: ["book club", "reading", "monthly", "library"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "dr4",
    title: "Ivory Cup Antiques & Estate Sale",
    category: "Events",
    subcategory: "Community Gathering",
    description: "A rotating antiques and estate sale featuring local dealers and estate liquidators. A good source for furniture, art, jewelry, and vintage housewares. Check the library bulletin board for upcoming dates.",
    location: "Deep River Town Hall Grounds",
    city: "Deep River",
    state: "CT",
    cost: "Free to browse",
    tags: ["antiques", "estate sale", "vintage", "shopping"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── ESSEX ────────────────────────────────────────────────────────────────

  {
    id: "e1",
    title: "Essex Steam Train & Riverboat Ride",
    category: "Experiences",
    subcategory: "Adventure Days",
    description: "Board an 1920s steam train from Essex Station, ride through the Connecticut River Valley, then transfer to a riverboat for a cruise up the river and back. Two hours of pure New England charm. Book ahead in summer.",
    location: "Essex Steam Train Depot, 1 Railroad Ave",
    city: "Essex",
    state: "CT",
    cost: "$32 adults / $20 children",
    seniorDiscount: true,
    contact: "info@essexsteamtrain.com",
    tags: ["steam train", "riverboat", "family", "historic", "scenic"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "e2",
    title: "Friday Night Jazz at the Griswold Inn",
    category: "Events",
    subcategory: "Music",
    description: "The Tap Room at the Griswold Inn has hosted live music since 1776 — one of the oldest continuously operating taverns in America. Friday evenings feature jazz and sea chanteys. No reservation needed for the bar.",
    date: "2026-06-13",
    time: "8:00 PM",
    location: "Griswold Inn, 36 Main St",
    city: "Essex",
    state: "CT",
    cost: "Free (no cover)",
    tags: ["jazz", "live music", "historic", "tavern", "Friday"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "e3",
    title: "Connecticut River Museum",
    category: "Experiences",
    subcategory: "Field Quests",
    description: "Explore the history of the Connecticut River from its role in early American industry to the remarkable turtle grass restoration happening today. The museum sits right at the water's edge in a restored 1878 steamboat warehouse.",
    location: "Connecticut River Museum, 67 Main St",
    city: "Essex",
    state: "CT",
    cost: "$10 adults / $8 seniors / free under 6",
    seniorDiscount: true,
    contact: "info@ctrivermuseum.org",
    tags: ["museum", "history", "river", "maritime", "culture"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "e4",
    title: "Essex Village Walking Tour",
    category: "Experiences",
    subcategory: "Self-Guided",
    description: "One of the best-preserved 18th-century villages in New England. Pick up a walking map at the Connecticut River Museum or the library and explore captains' houses, historic churches, and the working waterfront. About 1.5 miles, flat terrain.",
    location: "Start at Main St & Pratt St",
    city: "Essex",
    state: "CT",
    cost: "Free",
    tags: ["walking tour", "historic", "self-guided", "village", "architecture"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "e5",
    title: "Essex Corinthian Yacht Club Open Sail",
    category: "Groups",
    subcategory: "Walking Groups",
    description: "Experienced sailors welcome for weekend open sail days on the Connecticut River. The club offers informal crewing opportunities for visitors. Check the bulletin board at the dock for current schedule.",
    location: "Essex Corinthian Yacht Club, 1 Ferry St",
    city: "Essex",
    state: "CT",
    cost: "Guest fee varies",
    tags: ["sailing", "boating", "river", "social", "outdoors"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "e6",
    title: "Senior Center Tuesday Lunch & Bingo",
    category: "Events",
    subcategory: "Community Gathering",
    description: "Hot lunch served at noon followed by bingo every Tuesday at the Essex Senior Center. Open to all adults 55+. Good food, good company, no pressure to play.",
    date: "2026-06-10",
    time: "12:00 PM",
    location: "Essex Senior Center, 31 River Rd",
    city: "Essex",
    state: "CT",
    cost: "$4 suggested donation",
    seniorDiscount: true,
    contact: "seniors@essexct.gov",
    tags: ["seniors", "lunch", "bingo", "weekly", "social"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── OLD SAYBROOK ─────────────────────────────────────────────────────────

  {
    id: "os1",
    title: "Kate Katharine Hepburn Cultural Arts Center",
    category: "Experiences",
    subcategory: "Field Quests",
    description: "The Katharine Hepburn Cultural Arts Center — known locally as 'The Kate' — presents theater, music, film, and lectures in Hepburn's hometown. Check the current season calendar for upcoming shows. The building itself is worth a visit.",
    location: "The Kate, 300 Main St",
    city: "Old Saybrook",
    state: "CT",
    cost: "Varies by event",
    contact: "info@katharinehepburntheater.org",
    tags: ["theater", "arts", "Katharine Hepburn", "culture", "music"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "os2",
    title: "Saybrook Point Sunrise Walk",
    category: "Experiences",
    subcategory: "Adventure Days",
    description: "Walk out to Saybrook Point at dawn and watch the sun rise over the Connecticut River mouth where it meets Long Island Sound. One of the most peaceful thirty minutes you can spend. Free parking at the marina before 8 AM.",
    location: "Saybrook Point Marina, 2 Bridge St",
    city: "Old Saybrook",
    state: "CT",
    cost: "Free",
    tags: ["sunrise", "walking", "river", "sound", "peaceful"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "os3",
    title: "Old Saybrook Pickleball Club",
    category: "Groups",
    subcategory: "Pickleball",
    description: "Open play Tuesday and Thursday mornings and Saturday afternoons at Harvey's Beach courts. All skill levels. Bring your own paddle or borrow one. Friendly group — beginners always welcome.",
    location: "Harvey's Beach, Old Saybrook",
    city: "Old Saybrook",
    state: "CT",
    cost: "Free",
    contact: "saybrookpickleball@gmail.com",
    tags: ["pickleball", "sports", "active", "social", "weekly"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "os4",
    title: "Main Street Stroll & Shop — Old Saybrook",
    category: "Experiences",
    subcategory: "Self-Guided",
    description: "Old Saybrook's Main Street runs a mile through an honest New England downtown — independent bookshops, galleries, hardware stores, ice cream, and a diner that's been there forever. No chain stores. Worth a slow afternoon.",
    location: "Main St, Old Saybrook",
    city: "Old Saybrook",
    state: "CT",
    cost: "Free to stroll",
    tags: ["shopping", "walking", "downtown", "local", "self-guided"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "os5",
    title: "Lyme-Old Lyme Garden Club Plant Sale",
    category: "Events",
    subcategory: "Community Gathering",
    description: "Annual plant sale with native perennials, annuals, herbs, and vegetable starts grown by local gardeners. Everything is well-labeled and members are on hand to answer questions. Cash and check only.",
    date: "2026-06-14",
    time: "9:00 AM",
    location: "Old Saybrook Town Green",
    city: "Old Saybrook",
    state: "CT",
    cost: "Prices vary",
    tags: ["plants", "gardening", "community", "native plants", "annual"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── OLD LYME ─────────────────────────────────────────────────────────────

  {
    id: "ol1",
    title: "Florence Griswold Museum",
    category: "Experiences",
    subcategory: "Field Quests",
    description: "The birthplace of American Impressionism. The Florence Griswold Museum preserves the boarding house where Childe Hassam, Willard Metcalf, and dozens of other artists lived and worked in the early 1900s. The riverside gardens and grounds are lovely on their own.",
    location: "Florence Griswold Museum, 96 Lyme St",
    city: "Old Lyme",
    state: "CT",
    cost: "$12 adults / $10 seniors / free Fridays 5–8 PM",
    seniorDiscount: true,
    contact: "info@florencegriswoldmuseum.org",
    tags: ["museum", "impressionism", "art", "history", "gardens"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "ol2",
    title: "Black Hall River Kayak Launch",
    category: "Experiences",
    subcategory: "Adventure Days",
    description: "The Black Hall River offers some of the most serene flatwater paddling on the shoreline. Launch from the town ramp and explore tidal marshes that attract egrets, ospreys, and shorebirds. Best at high tide.",
    location: "Black Hall River Boat Ramp, Neck Rd",
    city: "Old Lyme",
    state: "CT",
    cost: "Free",
    tags: ["kayaking", "paddling", "marsh", "birding", "nature"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "ol3",
    title: "Lyme Street Walking Tour",
    category: "Experiences",
    subcategory: "Self-Guided",
    description: "Lyme Street is one of the most beautiful elm-lined streets in New England. A self-guided tour brochure (available at the museum) walks you past historic homes, the First Congregational Church, and the houses where Impressionist painters once lived.",
    location: "Lyme St, Old Lyme (start at museum)",
    city: "Old Lyme",
    state: "CT",
    cost: "Free",
    tags: ["walking", "historic", "architecture", "self-guided", "elms"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "ol4",
    title: "Old Lyme Art Association Open Studio",
    category: "Events",
    subcategory: "Classes",
    description: "Drop-in open studio sessions for painters at the Lyme Art Association gallery on Fridays. Working artists share space and instruction in a relaxed setting. All media welcome. No registration required.",
    date: "2026-06-13",
    time: "10:00 AM",
    location: "Lyme Art Association, 90 Lyme St",
    city: "Old Lyme",
    state: "CT",
    cost: "$10 suggested",
    tags: ["art", "painting", "open studio", "creative", "weekly"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "ol5",
    title: "Old Lyme Garden Club",
    category: "Groups",
    subcategory: "Garden Clubs",
    description: "Active garden club with monthly meetings, seasonal garden tours, conservation projects, and a strong focus on native plantings. Meetings include a program speaker. Visitors welcome — first meeting free.",
    location: "Old Lyme Town Hall, 52 Lyme St",
    city: "Old Lyme",
    state: "CT",
    cost: "$25/year membership",
    tags: ["gardening", "native plants", "community", "monthly"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── WESTBROOK ────────────────────────────────────────────────────────────

  {
    id: "wb1",
    title: "Westbrook Town Beach — Morning Walk",
    category: "Experiences",
    subcategory: "Adventure Days",
    description: "The town beach is free for early morning access before 9 AM. The walk at low tide from the pavilion to the jetty and back is about a mile on packed sand. Bring binoculars — piping plovers and terns nest nearby in June.",
    location: "Westbrook Town Beach, Flat Rock Rd",
    city: "Westbrook",
    state: "CT",
    cost: "Free (before 9 AM)",
    tags: ["beach", "walking", "birding", "morning", "free"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "wb2",
    title: "Menunketesuck River Nature Trail",
    category: "Experiences",
    subcategory: "Field Quests",
    description: "A short, peaceful trail following the Menunketesuck River through woodland and marsh. The loop is about 1.5 miles on easy terrain. Good for a quiet hour outdoors — turtles sunning on logs, herons in the shallows.",
    location: "Menunketesuck Trail, Essex Rd trailhead",
    city: "Westbrook",
    state: "CT",
    cost: "Free",
    tags: ["hiking", "nature", "river", "turtles", "easy"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "wb3",
    title: "Westbrook Wednesday Walking Group",
    category: "Groups",
    subcategory: "Walking Groups",
    description: "Casual walking group that meets every Wednesday at 8 AM at the town green. Routes vary — beach, rail trail, neighborhoods. About 3–4 miles at a comfortable pace. Coffee at Starbucks after. All welcome.",
    location: "Westbrook Town Green, Boston Post Rd",
    city: "Westbrook",
    state: "CT",
    cost: "Free",
    tags: ["walking", "weekly", "social", "fitness", "outdoors"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "wb4",
    title: "Shore Line East Train to New Haven",
    category: "Experiences",
    subcategory: "Adventure Days",
    description: "Take the Shore Line East train from Westbrook to New Haven for a day in the city — Yale galleries, incredible food, the Amistad at the dock. Round trip under $15. No parking hassles. A genuinely good day trip.",
    location: "Westbrook Station, 1 Railroad Ave",
    city: "Westbrook",
    state: "CT",
    cost: "~$14 round trip",
    seniorDiscount: true,
    tags: ["train", "day trip", "New Haven", "Yale", "adventure"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── CLINTON ──────────────────────────────────────────────────────────────

  {
    id: "cl1",
    title: "Clinton Town Beach Sunrise",
    category: "Experiences",
    subcategory: "Adventure Days",
    description: "Clinton's town beach faces east across Long Island Sound. Come before 6 AM in summer and you'll often have the entire beach to yourself for the sunrise. The walk along the water's edge is a genuine way to start the day.",
    location: "Clinton Town Beach, Waterside Ln",
    city: "Clinton",
    state: "CT",
    cost: "Free (residents) / $5 non-residents",
    tags: ["beach", "sunrise", "walking", "peaceful", "morning"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "cl2",
    title: "Henry Carter Hull Library Lecture Series",
    category: "Events",
    subcategory: "Lectures",
    description: "The Clinton library runs a year-round free lecture series featuring local historians, naturalists, authors, and community figures. Events are held in the library community room. No registration required — just show up.",
    location: "Henry Carter Hull Library, 10 Killingworth Tpke",
    city: "Clinton",
    state: "CT",
    cost: "Free",
    contact: "library@clintonct.org",
    tags: ["lecture", "library", "history", "community", "free"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "cl3",
    title: "Clinton Harbor Walk",
    category: "Experiences",
    subcategory: "Self-Guided",
    description: "A quiet walk along Clinton Harbor from the town dock to the breakwater and back. Watch lobster boats unload, sailboats come and go, and osprey fish in the channel. Best at low tide when the sandbars appear.",
    location: "Clinton Town Dock, Harbor Park Rd",
    city: "Clinton",
    state: "CT",
    cost: "Free",
    tags: ["harbor", "walking", "boats", "osprey", "peaceful"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "cl4",
    title: "Clinton Volunteer Trail Stewards",
    category: "Groups",
    subcategory: "Volunteer Groups",
    description: "Help maintain Clinton's network of walking trails — clearing brush, marking paths, and building bog bridges. Work parties go out one Saturday morning per month. Good outdoor work with good people. All tools provided.",
    location: "Meets at Clinton Town Hall, 54 E Main St",
    city: "Clinton",
    state: "CT",
    cost: "Free",
    contact: "trails@clintonct.org",
    tags: ["volunteer", "trails", "outdoors", "conservation", "monthly"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "cl5",
    title: "Clinton Book Club at the Library",
    category: "Groups",
    subcategory: "Book Clubs",
    description: "Monthly book discussion at the Clinton library. The group leans toward literary fiction and narrative nonfiction. Books available through the library's holds system. Meets the third Tuesday evening at 7 PM.",
    location: "Henry Carter Hull Library, 10 Killingworth Tpke",
    city: "Clinton",
    state: "CT",
    cost: "Free",
    contact: "library@clintonct.org",
    tags: ["book club", "reading", "monthly", "library", "fiction"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── SHARED / MULTI-TOWN SERVICES ─────────────────────────────────────────

  {
    id: "sv1",
    title: "Valley Shore Visiting Nurse Association",
    category: "Services",
    subcategory: "Senior Services",
    description: "In-home nursing, physical therapy, and health aide services for residents of the lower Connecticut River Valley. Accepts Medicare, Medicaid, and most private insurance. Sliding-scale fees available. Call for an assessment.",
    location: "Serving Chester, Deep River, Essex, and surrounding towns",
    city: "Essex",
    state: "CT",
    cost: "Varies / insurance accepted",
    seniorDiscount: true,
    contact: "info@valleyshorevna.org",
    tags: ["home health", "nursing", "seniors", "Medicare", "in-home care"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "sv2",
    title: "Connecticut River Valley Senior Center — Transportation",
    category: "Services",
    subcategory: "Senior Services",
    description: "Volunteer driver program for adults 60+ who need rides to medical appointments, grocery shopping, and other essential errands. Advance scheduling required. No fee — a donation is appreciated but never required.",
    location: "Deep River Senior Center, 6 Kirtland St",
    city: "Deep River",
    state: "CT",
    cost: "Free (donations welcome)",
    seniorDiscount: true,
    contact: "seniors@deepriverct.us",
    tags: ["transportation", "seniors", "volunteer drivers", "rides", "medical"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "sv3",
    title: "Shoreline Soup Kitchens & Food Pantries",
    category: "Services",
    subcategory: "Senior Services",
    description: "A network of food pantries serving residents across the shoreline — Chester, Deep River, Essex, Old Saybrook, Old Lyme, Westbrook, and Clinton. No income verification required. Call ahead for hours and pickup locations.",
    location: "Multiple locations",
    city: "Old Saybrook",
    state: "CT",
    cost: "Free",
    contact: "info@shorelinesoups.org",
    tags: ["food pantry", "community support", "free food", "shoreline"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── ONE PENDING COMMUNITY SUBMISSION ────────────────────────────────────

  {
    id: "pend1",
    title: "Early Morning Birding Walk — Great Island Marsh",
    category: "Events",
    subcategory: "Recreation",
    description: "Join local birder Tom Andersen for a dawn walk through Great Island Marsh in Old Lyme — one of the most significant coastal marshes on the Connecticut shoreline. Peak shorebird migration season. Bring binoculars and boots.",
    date: "2026-06-21",
    time: "5:30 AM",
    location: "Great Island Boat Launch, Smith Neck Rd",
    city: "Old Lyme",
    state: "CT",
    cost: "Free",
    contact: "tandersen.birds@gmail.com",
    tags: ["birding", "marsh", "shorebirds", "dawn", "guided"],
    status: "pending",
    submittedBy: "community",
    createdAt: "2026-06-07T14:00:00Z",
  },

  // ── FUNDRAISERS ──────────────────────────────────────────────────────────────

  {
    id: "fund1",
    title: "Chester Library Summer Reading Fund",
    category: "Fundraisers",
    subcategory: "Community Fund",
    description: "Help us keep summer reading alive for every kid in Chester. Donations fund new books, reading prizes, and three weeks of programming at the Chester Public Library. Every dollar stays local.",
    location: "Chester Public Library, 21 West Main St",
    city: "Chester",
    state: "CT",
    cost: "Donate any amount",
    url: "https://chesterlibrary.org",
    tags: ["library", "kids", "reading", "donate", "community"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-04T10:00:00Z",
  },
  {
    id: "fund2",
    title: "Essex Volunteer Fire Company Annual Appeal",
    category: "Fundraisers",
    subcategory: "Emergency Services Fund",
    description: "The Essex Volunteer Fire Company responds to over 400 calls a year — entirely with unpaid volunteers. Their annual appeal funds equipment, training, and gear upgrades. Support the neighbors who run toward the fire.",
    location: "Essex Fire Station, 8 Novelty Lane",
    city: "Essex",
    state: "CT",
    cost: "Donate any amount",
    tags: ["fire", "volunteer", "donate", "safety", "essex"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-03T10:00:00Z",
  },
  {
    id: "fund3",
    title: "Deep River Founder's Day Festival Fund",
    category: "Fundraisers",
    subcategory: "Community Event Fund",
    description: "Founder's Day is Deep River's biggest celebration and it runs entirely on community donations. This year's goal covers the Ancient Fife & Drum muster, fireworks, and the Main Street parade. Help keep the tradition going.",
    date: "2026-07-04",
    location: "Main Street, Deep River",
    city: "Deep River",
    state: "CT",
    cost: "Donate any amount",
    tags: ["founders day", "parade", "fife drum", "celebration", "donate"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-02T10:00:00Z",
  },
  {
    id: "fund4",
    title: "Old Lyme Land Trust: Preserve the River's Edge",
    category: "Fundraisers",
    subcategory: "Land Conservation Fund",
    description: "The Old Lyme Land Trust is raising funds to protect 14 acres of CT River waterfront from development. This is a once-in-a-generation opportunity to keep this land wild and public. Your gift is tax-deductible.",
    location: "Old Lyme, CT",
    city: "Old Lyme",
    state: "CT",
    cost: "Donate any amount",
    tags: ["land trust", "conservation", "river", "nature", "donate"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },

  // ── VOLUNTEERS ────────────────────────────────────────────────────────────────

  {
    id: "vol1",
    title: "Connecticut River Cleanup — Chester to Essex",
    category: "Volunteers",
    subcategory: "River Stewardship",
    description: "Join the annual Connecticut River shoreline cleanup. Gloves, bags, and refreshments provided. Meet at the Chester boat launch at 8 AM. All ages welcome — it's a great morning and the river thanks you.",
    date: "2026-06-21",
    time: "8:00 AM",
    location: "Chester Boat Launch, River Rd",
    city: "Chester",
    state: "CT",
    cost: "Free",
    tags: ["cleanup", "river", "environment", "outdoors", "family"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-04T10:00:00Z",
  },
  {
    id: "vol2",
    title: "Deep River Food Pantry — Weekly Volunteers Needed",
    category: "Volunteers",
    subcategory: "Food Security",
    description: "The Deep River Food Pantry serves over 80 families each week and needs volunteers every Tuesday and Thursday morning. Tasks include sorting donations, stocking shelves, and greeting clients. Training provided.",
    time: "9:00 AM",
    location: "Deep River Congregational Church, 1 Church St",
    city: "Deep River",
    state: "CT",
    cost: "Free",
    contact: "pantry@deepriverchurch.org",
    tags: ["food pantry", "weekly", "hunger", "community", "giving"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-03T10:00:00Z",
  },
  {
    id: "vol3",
    title: "Essex Land Trust Trail Crew",
    category: "Volunteers",
    subcategory: "Trail Maintenance",
    description: "Work alongside the Essex Land Trust to maintain and improve trails across town. No experience needed — just sturdy shoes and a good attitude. The crew meets the first Saturday of each month at 8:30 AM.",
    time: "8:30 AM",
    location: "Meets at Town Hall parking lot, Essex",
    city: "Essex",
    state: "CT",
    cost: "Free",
    tags: ["trails", "outdoors", "land trust", "monthly", "conservation"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-02T10:00:00Z",
  },
  {
    id: "vol4",
    title: "Old Saybrook Hospital Auxiliary — Gift Shop Volunteers",
    category: "Volunteers",
    subcategory: "Hospital Support",
    description: "The Middlesex Health Old Saybrook location is looking for friendly faces to help run the auxiliary gift shop. Shifts are 3 hours, flexible days. Proceeds support patient comfort funds. Perfect for retirees or anyone with a few hours a week.",
    location: "Middlesex Health, Old Saybrook Campus",
    city: "Old Saybrook",
    state: "CT",
    cost: "Free",
    contact: "auxiliary@middlesexhealth.org",
    tags: ["hospital", "gift shop", "flexible", "seniors", "community"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "vol5",
    title: "Westbrook Beach Ambassadors",
    category: "Volunteers",
    subcategory: "Community Stewardship",
    description: "Help keep Westbrook's beaches clean and welcoming all summer. Ambassadors do a 30-minute beach walk a few mornings a week, pick up litter, and report issues to the parks department. Flexible schedule, big impact.",
    location: "Westbrook Town Beach, Beach St",
    city: "Westbrook",
    state: "CT",
    cost: "Free",
    tags: ["beach", "environment", "flexible", "summer", "outdoor"],
    status: "published",
    submittedBy: "curator",
    createdAt: "2026-06-01T10:00:00Z",
  },
];

export function getListings(filters?: {
  city?: string;
  category?: Category;
  status?: Status;
}): Listing[] {
  let results = [...listings];
  if (filters?.city) results = results.filter((l) => l.city === filters.city);
  if (filters?.category) results = results.filter((l) => l.category === filters.category);
  if (filters?.status) results = results.filter((l) => l.status === filters.status);
  return results.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
}

export function getCities(): string[] {
  return ["Chester", "Deep River", "Essex", "Old Saybrook", "Old Lyme", "Westbrook", "Clinton"];
}

export function getListing(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}

export function addListing(data: Omit<Listing, "id" | "createdAt">): Listing {
  const listing: Listing = {
    ...data,
    id: Date.now().toString(),
    createdAt: new Date().toISOString(),
  };
  listings.unshift(listing);
  return listing;
}

export function updateListing(id: string, updates: Partial<Listing>): Listing | null {
  const idx = listings.findIndex((l) => l.id === id);
  if (idx === -1) return null;
  listings[idx] = { ...listings[idx], ...updates };
  return listings[idx];
}

export function deleteListing(id: string): boolean {
  const idx = listings.findIndex((l) => l.id === id);
  if (idx === -1) return false;
  listings.splice(idx, 1);
  return true;
}
