// Run once to seed Supabase with all current listings:
// node scripts/seed.mjs

import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

// Load .env.local manually
const envPath = join(dirname(fileURLToPath(import.meta.url)), "../.env.local");
const env = readFileSync(envPath, "utf8");
for (const line of env.split("\n")) {
  const [key, ...rest] = line.split("=");
  if (key && rest.length) process.env[key.trim()] = rest.join("=").trim();
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

// All current listings from data.ts — camelCase → snake_case for DB
const listings = [
  { id:"c1", title:"Chester-Hadlyme Ferry Crossing", category:"Experiences", subcategory:"Adventure Days", description:"Hop aboard the second-oldest continuously operating ferry in the country. The Selden III carries you across the Connecticut River in just a few minutes — a small trip that feels like stepping back in time. Runs spring through fall.", location:"Ferry Landing, 148 River Rd", city:"Chester", state:"CT", cost:"$3 per person", senior_discount:false, tags:["ferry","river","historic","family","outdoors"], status:"published", submitted_by:"curator" },
  { id:"c2", title:"Saturday Morning at the Chester Farmers Market", category:"Events", subcategory:"Community Gathering", description:"Fresh produce, local honey, handmade breads, cut flowers, and familiar faces every Saturday morning in the village center. The heart of Chester's weekly rhythm.", date:"2026-06-13", time:"9:00 AM", location:"Chester Town Center, Route 154", city:"Chester", state:"CT", cost:"Free to attend", senior_discount:false, tags:["farmers market","local food","weekly","community"], status:"published", submitted_by:"curator" },
  { id:"c3", title:"Gallery Crawl — Chester Village Arts District", category:"Experiences", subcategory:"Self-Guided", description:"Chester's Main Street packs more galleries per block than almost anywhere in Connecticut. Pick up a gallery map at the Pattaconk Tavern and wander at your own pace — ceramics, painting, sculpture, and jewelry from working artists.", location:"Main St, Chester Village", city:"Chester", state:"CT", cost:"Free", senior_discount:false, tags:["art","galleries","self-guided","walking","village"], status:"published", submitted_by:"curator" },
  { id:"c4", title:"Chester Creative Arts Summer Concert Series", category:"Events", subcategory:"Live Music", description:"Free outdoor concerts on the Chester green all summer long. Bring a blanket, a picnic, and your neighbors. Local and regional musicians play everything from folk to jazz to classical.", location:"Chester Town Green", city:"Chester", state:"CT", cost:"Free", senior_discount:false, tags:["music","concerts","outdoor","summer","free"], status:"published", submitted_by:"curator" },
  { id:"c5", title:"Chester Garden Club Plant Sale", category:"Events", subcategory:"Community Sale", description:"Annual spring plant sale with perennials, annuals, herbs, and vegetable starts — all grown by local gardeners. Great deals and great conversation.", location:"Chester Library Grounds", city:"Chester", state:"CT", cost:"Varies", senior_discount:false, tags:["garden","plants","sale","spring","community"], status:"published", submitted_by:"curator" },
  { id:"c6", title:"Chester Volunteer Fire Company", category:"Volunteers", subcategory:"Emergency Services", description:"The Chester Volunteer Fire Company is always looking for dedicated community members to train as firefighters or support staff. Serve your neighbors and build lifelong friendships.", location:"Chester Fire House, 29 Liberty St", city:"Chester", state:"CT", cost:"Free", senior_discount:false, tags:["volunteer","fire","emergency","community service"], status:"published", submitted_by:"curator" },

  { id:"dr1", title:"Deep River Muster & Parade", category:"Events", subcategory:"Town Tradition", description:"The largest fife and drum muster in the world, held every July in Deep River. Dozens of Ancient Fife and Drum Corps from across the country march through town in full colonial regalia. A genuine piece of Connecticut heritage.", date:"2026-07-18", time:"2:00 PM", location:"Main St, Deep River", city:"Deep River", state:"CT", cost:"Free", senior_discount:false, tags:["parade","fife and drum","tradition","july","family"], status:"published", submitted_by:"curator" },
  { id:"dr2", title:"Deep River Farmers Market", category:"Events", subcategory:"Community Gathering", description:"Local vendors bring fresh produce, baked goods, and handcrafted items to the center of town. A friendly weekly gathering for neighbors.", location:"Town Center, Deep River", city:"Deep River", state:"CT", cost:"Free to attend", senior_discount:false, tags:["farmers market","local","weekly","produce"], status:"published", submitted_by:"curator" },
  { id:"dr3", title:"Kalmia Club Garden Tour", category:"Experiences", subcategory:"Self-Guided", description:"Tour the private and public gardens of Deep River on this annual walk. See how your neighbors grow things — from formal cutting gardens to wild native plantings.", location:"Various locations, Deep River", city:"Deep River", state:"CT", cost:"$10", senior_discount:false, tags:["gardens","walking tour","nature","community"], status:"published", submitted_by:"curator" },
  { id:"dr4", title:"Deep River Community Cleanup Day", category:"Volunteers", subcategory:"Town Stewardship", description:"Join neighbors for a morning of cleanup along the river trail and town green. Tools and bags provided. Finish with coffee and donuts at Town Hall.", location:"Deep River Town Hall", city:"Deep River", state:"CT", cost:"Free", senior_discount:false, tags:["volunteer","environment","cleanup","community"], status:"published", submitted_by:"curator" },

  { id:"e1", title:"Essex Steam Train & Riverboat Ride", category:"Experiences", subcategory:"Adventure Days", description:"Board a vintage steam train through the Connecticut River Valley, then transfer to a riverboat for a scenic cruise. One of New England's most beloved excursions — timeless for all ages.", location:"Essex Train Station, 1 Railroad Ave", city:"Essex", state:"CT", cost:"$30–$38", senior_discount:true, tags:["train","riverboat","historic","family","scenic"], status:"published", submitted_by:"curator" },
  { id:"e2", title:"Essex Village Stroll & Antique Row", category:"Experiences", subcategory:"Self-Guided", description:"Essex village is one of the best-preserved 18th-century streetscapes in New England. Walk Main Street from the river up through antique shops, galleries, and the historic Griswold Inn, open since 1776.", location:"Main St, Essex Village", city:"Essex", state:"CT", cost:"Free", senior_discount:false, tags:["walking","antiques","historic","village","self-guided"], status:"published", submitted_by:"curator" },
  { id:"e3", title:"Connecticut River Museum", category:"Experiences", subcategory:"Museums & History", description:"Explore the full story of the Connecticut River — from the indigenous Pequot peoples to the industrial age — at this waterfront museum. Rotating exhibits and a full-size replica of the first American submarine.", location:"67 Main St, Essex", city:"Essex", state:"CT", cost:"$10 adults / $6 children", senior_discount:true, tags:["museum","history","river","submarine","family"], status:"published", submitted_by:"curator" },
  { id:"e4", title:"Friday Evening Concerts on the Essex Green", category:"Events", subcategory:"Live Music", description:"Pack a lawn chair and join the whole town for free live music on the Essex town green every Friday evening in summer. Local bands play rock, folk, and everything in between.", date:"2026-07-10", time:"6:30 PM", location:"Essex Town Green", city:"Essex", state:"CT", cost:"Free", senior_discount:false, tags:["concert","music","outdoor","summer","free"], status:"published", submitted_by:"curator" },
  { id:"e5", title:"Ivoryton Playhouse Summer Season", category:"Events", subcategory:"Theatre", description:"One of the oldest continuously operating summer theaters in the U.S. Professional productions of musicals and dramas just minutes from the river. Check their schedule for current shows.", location:"103 Main St, Ivoryton (Essex)", city:"Essex", state:"CT", cost:"$35–$55", senior_discount:false, url:"https://ivorytonplayhouse.org", tags:["theater","performance","arts","summer","professional"], status:"published", submitted_by:"curator" },
  { id:"e6", title:"Senior Center Tuesday Lunch & Bingo", category:"Events", subcategory:"Senior Programs", description:"Hot lunch followed by bingo every Tuesday at the Essex Senior Center. Open to all seniors — whether you've been coming for years or it's your first time. Transportation available on request.", date:"2026-07-08", time:"11:30 AM", location:"Essex Senior Center, 14 Woods Lane", city:"Essex", state:"CT", cost:"$4 lunch", senior_discount:true, tags:["senior","lunch","bingo","social","weekly"], status:"published", submitted_by:"curator" },

  { id:"os1", title:"Old Saybrook Farmers Market", category:"Events", subcategory:"Community Gathering", description:"One of the liveliest markets on the shoreline — fresh vegetables, local fish, prepared foods, artisan crafts, and live music on the green. Rain or shine.", location:"Kate's Field, Old Saybrook", city:"Old Saybrook", state:"CT", cost:"Free to attend", senior_discount:false, tags:["farmers market","local","weekly","food","music"], status:"published", submitted_by:"curator" },
  { id:"os2", title:"Katharine Hepburn Cultural Arts Center", category:"Events", subcategory:"Theatre & Film", description:"The Kate (as the locals call it) hosts theater, film, music, and comedy in an intimate restored theater downtown. Check their calendar — something's always on.", location:"300 Main St, Old Saybrook", city:"Old Saybrook", state:"CT", cost:"Varies by show", senior_discount:false, url:"https://thekate.org", tags:["theater","film","arts","music","performance"], status:"published", submitted_by:"curator" },
  { id:"os3", title:"Saybrook Point Lighthouse Walk", category:"Experiences", subcategory:"Adventure Days", description:"Walk out to Saybrook Point and see the lighthouse at the mouth of the Connecticut River. The view across the Sound on a clear day is as good as it gets on the shoreline.", location:"Saybrook Point, Old Saybrook", city:"Old Saybrook", state:"CT", cost:"Free", senior_discount:false, tags:["lighthouse","walking","river","sound","scenic"], status:"published", submitted_by:"curator" },
  { id:"os4", title:"Old Saybrook Garden Club Plant Exchange", category:"Events", subcategory:"Community Sale", description:"Bring divisions from your own garden and swap with neighbors. Always a great variety — perennials, ground covers, herbs, and more. Free and open to all.", location:"Old Saybrook Town Green", city:"Old Saybrook", state:"CT", cost:"Free", senior_discount:false, tags:["garden","plants","swap","community","spring"], status:"published", submitted_by:"curator" },
  { id:"os5", title:"Estuary Council Senior Center", category:"Services", subcategory:"Senior Programs", description:"Transportation, meals, social programs, and wellness activities for adults 60+ across the shoreline towns. Call to learn what's available this week.", location:"220 Main St, Old Saybrook", city:"Old Saybrook", state:"CT", cost:"Low / sliding scale", senior_discount:false, contact:"info@estuary.org", tags:["senior","services","transportation","meals","wellness"], status:"published", submitted_by:"curator" },

  { id:"ol1", title:"Florence Griswold Museum", category:"Experiences", subcategory:"Museums & History", description:"The home of American Impressionism — the Lyme Art Colony gathered here in the early 1900s and left paintings on the dining room walls. Stunning grounds along the Lieutenant River. One of Connecticut's great treasures.", location:"96 Lyme St, Old Lyme", city:"Old Lyme", state:"CT", cost:"$15 adults / $13 seniors", senior_discount:true, url:"https://florencegriswoldmuseum.org", tags:["museum","art","impressionism","historic","garden"], status:"published", submitted_by:"curator" },
  { id:"ol2", title:"Old Lyme Midsummer Festival", category:"Events", subcategory:"Town Tradition", description:"A beloved community tradition every July — arts and crafts vendors, food, live music, and family activities centered around the historic town green. Festive and free.", date:"2026-07-12", time:"10:00 AM", location:"Old Lyme Town Green", city:"Old Lyme", state:"CT", cost:"Free", senior_discount:false, tags:["festival","arts","crafts","music","family","community"], status:"published", submitted_by:"curator" },
  { id:"ol3", title:"Lyme Art Association Summer Exhibition", category:"Experiences", subcategory:"Art & Galleries", description:"The oldest continuous art association in America. Their summer show fills the gallery with paintings and sculpture by regional artists. Always worth a stop when visiting the Griswold Museum next door.", location:"90 Lyme St, Old Lyme", city:"Old Lyme", state:"CT", cost:"Free", senior_discount:false, tags:["art","gallery","painting","summer","exhibition"], status:"published", submitted_by:"curator" },
  { id:"ol4", title:"Old Lyme Land Trust Nature Walks", category:"Experiences", subcategory:"Nature & Trails", description:"The Old Lyme Land Trust maintains miles of trails through forests, wetlands, and meadows. Self-guided any time — pick up a trail map at Town Hall or download it online.", location:"Various trailheads, Old Lyme", city:"Old Lyme", state:"CT", cost:"Free", senior_discount:false, tags:["hiking","nature","trails","land trust","self-guided"], status:"published", submitted_by:"curator" },

  { id:"wb1", title:"Westbrook Town Beach", category:"Experiences", subcategory:"Adventure Days", description:"One of the most accessible public beaches on the CT shoreline. Wide sandy stretch on Long Island Sound, gentle surf, and a relaxed small-town vibe. Town beach sticker required for parking in summer.", location:"Seaside Ave, Westbrook", city:"Westbrook", state:"CT", cost:"Free (parking fee in season)", senior_discount:false, tags:["beach","swimming","sound","family","summer"], status:"published", submitted_by:"curator" },
  { id:"wb2", title:"Westbrook Outlets Stroll", category:"Experiences", subcategory:"Local Shopping", description:"More than 60 designer and name-brand outlet stores in a pleasant open-air setting. Good for a browse whether or not you're in the market for anything.", location:"314 Flat Rock Place, Westbrook", city:"Westbrook", state:"CT", cost:"Free to browse", senior_discount:false, tags:["shopping","outlets","walking","casual"], status:"published", submitted_by:"curator" },
  { id:"wb3", title:"Westbrook Community Garden", category:"Groups", subcategory:"Gardening Circle", description:"Plot holders and volunteers tend the Westbrook Community Garden together. New members welcome — plots available, or just come to help and learn on volunteer days.", location:"Westbrook Community Garden", city:"Westbrook", state:"CT", cost:"Small annual fee for a plot", senior_discount:false, tags:["garden","community","volunteer","growing","neighbors"], status:"published", submitted_by:"curator" },
  { id:"wb4", title:"Shore Line East Train to New Haven", category:"Experiences", subcategory:"Adventure Days", description:"Hop the Shore Line East commuter train from Westbrook and ride to New Haven for a day out — Yale museums, the green, incredible pizza, and easy return by train. No car needed.", location:"Westbrook Train Station", city:"Westbrook", state:"CT", cost:"$9–$14 each way", senior_discount:true, tags:["train","day trip","new haven","adventure","transit"], status:"published", submitted_by:"curator" },

  { id:"cl1", title:"Clinton Crossing Premium Outlets", category:"Experiences", subcategory:"Local Shopping", description:"Well-known outlet center with major brands in a clean open-air setting. Easy access off I-95 — worth knowing about for a casual afternoon outing.", location:"20-A Killingworth Tpke, Clinton", city:"Clinton", state:"CT", cost:"Free to browse", senior_discount:false, tags:["shopping","outlets","casual"], status:"published", submitted_by:"curator" },
  { id:"cl2", title:"Clinton Farmers Market", category:"Events", subcategory:"Community Gathering", description:"Fresh local produce, homemade preserves, artisan goods, and good conversation every week at the Clinton farmers market. A great way to stock up and connect.", location:"Clinton Town Green", city:"Clinton", state:"CT", cost:"Free to attend", senior_discount:false, tags:["farmers market","local","weekly","community"], status:"published", submitted_by:"curator" },
  { id:"cl3", title:"Clinton Historical Society Walking Tour", category:"Experiences", subcategory:"Self-Guided", description:"Explore Clinton's colonial-era history on a self-guided walking tour. Pick up a map at the Historical Society and discover sea captains' homes, old churches, and the stories behind the streets.", location:"Clinton Historical Society, 103 E Main St", city:"Clinton", state:"CT", cost:"Free", senior_discount:false, tags:["history","walking","self-guided","colonial","architecture"], status:"published", submitted_by:"curator" },
  { id:"cl4", title:"Cedar Island Marina Sunset Walk", category:"Experiences", subcategory:"Nature & Trails", description:"Walk the breakwater at Cedar Island Marina at the end of the day. The sunsets over the marina and Hammonasset are consistently beautiful — a simple, free pleasure.", location:"Cedar Island Marina, Clinton", city:"Clinton", state:"CT", cost:"Free", senior_discount:false, tags:["sunset","marina","walking","nature","scenic"], status:"published", submitted_by:"curator" },

  { id:"sv1", title:"Valley Shore VNA Home Health Services", category:"Services", subcategory:"Health & Wellness", description:"The Valley Shore Visiting Nurse Association provides skilled nursing, physical therapy, and home health aide services throughout the shoreline towns. Call to learn what's covered by Medicare or insurance.", location:"Serving all shoreline towns", city:"Old Saybrook", state:"CT", cost:"Covered by Medicare/insurance", senior_discount:true, contact:"info@vsna.org", tags:["health","nursing","home care","senior","medicare"], status:"published", submitted_by:"curator" },
  { id:"sv2", title:"Senior Center Transportation Program", category:"Services", subcategory:"Transportation", description:"Coordinated transportation for seniors throughout the Valley Shore towns — medical appointments, shopping, and social programs. Call your town's senior center to schedule.", location:"Serving all shoreline towns", city:"Essex", state:"CT", cost:"Low / free for eligible seniors", senior_discount:true, contact:"transport@valleyshore.org", tags:["transportation","senior","medical","shopping","community"], status:"published", submitted_by:"curator" },
  { id:"sv3", title:"Valley Shore YMCA", category:"Services", subcategory:"Health & Wellness", description:"The Y serves members across the shoreline with fitness equipment, pools, group exercise, and community programs. Financial assistance available. Open to all ages.", location:"One Sunset Ave, Westbrook", city:"Westbrook", state:"CT", cost:"Membership varies", senior_discount:false, url:"https://valleyshoreymca.org", tags:["ymca","fitness","pool","wellness","community"], status:"published", submitted_by:"curator" },
];

const { error } = await supabase.from("listings").upsert(listings, { onConflict: "id" });

if (error) {
  console.error("Seed failed:", error.message);
  process.exit(1);
} else {
  console.log(`✅ Seeded ${listings.length} listings into Supabase.`);
}
